clients/urls.py
from django.conf.urls import patterns, url
from django.conf import settings
from django.conf.urls.static import static

from clients import views

urlpatterns = patterns('',
	url(r'^signup/$', views.new_client, name='signup'),
	url(r'^(?P<username>\w+)/$', views.client_account, name='account'),
	url(r'^(?P<username>\w+)/settings/$', views.client_settings, name='settings'),
	url(r'^(?P<username>\w+)/settings/del-goal/(?P<goal_id>[0-9]+)/$', views.delete_goal, name='del_goal'),
	url(r'^(?P<username>\w+)/settings/del-prof-pic/$', views.delete_profile_pic, name='del_prof_pic'),
	url(r'^(?P<username>\w+)/settings/del-ban-img/$', views.delete_banner_img, name='del_ban_img'),
)

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mydailyfit/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	url(r'^admin/', include(admin.site.urls)),
	url(r'^', include('splash.urls', namespace='splash')),
	url(r'^trainers/', include('trainers.urls', namespace='trainers')),
	url(r'^client/', include('clients.urls', namespace='clients')),
	url(r'^messages/', include('mdfMessaging.urls', namespace='messages')),
	url(r'^plans/', include('fitplans.urls', namespace='fitplans')),
)

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

splash/urls.py
from django.conf.urls import patterns, url
from django.conf import settings
from django.conf.urls.static import static

from splash import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^decisions/$', views.make_good_choices, name='choice'),
    #url(r'^trainersplash/$', views.trainerForHire, name='trainersplash'),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

splash/models.py
from django.db import models

# Create your models here.

class Signup(models.Model):
    email = models.EmailField(unique=True)

splash/forms.py
__author__ = 'austinbailey'

from django import forms
from django.core.mail import send_mail

from splash.models import Signup

my_default_errors = {
    'required': ' -\tThis field is required\n',
    'invalid': ' -\tPlease enter a valid value\n',
    'min_value': '-\tPlease enter a valid value\n',
    'max_value': '-\tPlease enter a valid value\n'
}


class searchForm(forms.Form):
    searchQ = forms.EmailField(
        widget=forms.TextInput(
            attrs={
                'placeholder': 'I want a personal trainers that can help me..',
                'class': 'signup-form-input',
                'id': 'searchQ'}
        )
    )

    '''
    Method used to create and save new user and send an email
    '''
    def submit_and_send(self):
        u_email = self.cleaned_data['searchQ']
        user = Signup.objects.create(email=u_email)
        user.save()
        send_mail('Thanks!', 'test', 'noreply@mydailyfit.com', [u_email], fail_silently=False)

class loginForm(forms.Form):
    username = forms.CharField(max_length=55, error_messages=my_default_errors,
                               widget=forms.TextInput(
                                   attrs={
                                       'placeholder': 'username',
                                       'class': 'signup-form-input m-b-1',
                                       'id': 'username'
                                   }
                               ))
    password = forms.CharField(max_length=55, error_messages=my_default_errors,
                               widget=forms.PasswordInput(
                                   attrs={
                                       'placeholder': 'password',
                                       'class': 'signup-form-input m-b-1',
                                       'id': 'password'
                                   }
                               ))

splash/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.core.urlresolvers import reverse
from datetime import datetime
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout

from splash.forms import searchForm, loginForm

from clients.models import Client
from trainers.models import Trainer

def index(request):
    year = datetime.now().year
    c_name = 'mydailyfit'
    new_form = searchForm()
    if request.method == 'POST':
        new_form = searchForm(request.POST)
        if new_form.is_valid():
            messages.add_message(request, messages.INFO, 'You\'re all set up to receive updates on our progress. This is going to be awesome!')
        else:
            context = {'year': year, 'c_name': c_name, 'new_form': new_form}
            return render(request, 'splash/base.html', context)
    context = {'year': year, 'c_name': c_name, 'new_form': new_form}
    return render(request, 'splash/base.html', context)

def make_good_choices(request):
    context = {}
    return render(request, 'splash/interrupt.html', context)

# View that handles authenticating and logging in a User
def user_login(request):
    if request.user.is_authenticated():
        try:
            trainer = Trainer.objects.get(user=request.user)
            return HttpResponseRedirect(reverse('trainers:account', args=(request.user.username,)))
        except Trainer.DoesNotExist:
            try:
                client = Client.objects.get(user=request.user)
                client.last_online = datetime.now()
                client.save()
                return HttpResponseRedirect(reverse('clients:account', args=(request.user.username,)))
            except Client.DoesNotExist:
                pass
    loginform = loginForm()
    # Make sure that the form was POSTed
    if request.method == 'POST':
        loginform = loginForm(request.POST)
        if loginform.is_valid():
            # Grab the submitted values
            username = request.POST['username']
            password = request.POST['password']
            # Attempt to grab a User object with submitted credentials
            user = authenticate(username=username, password=password)
            # If a User object was returned and the User is active,
            # log in the user and redirect the User to their profile page
            if user is not None:
                if user.is_active:
                    login(request, user)
                    try:
                        trainer = Trainer.objects.get(user=user)
                        return HttpResponseRedirect(reverse('trainers:account', args=(user.username,)))
                    except Trainer.DoesNotExist:
                        '''
                        Uncomment when CLient model is created
                        try:
                            client = Client.objects.get(user=user)
                            return HttpResponseRedirect(reverse('clients:account', args=(user.username,)))
                        except Client.DoesNotExist:
                            return HttpResponseRedirect(reverse('splash:login'))
                        '''
                        return HttpResponseRedirect(reverse('splash:login'))
                # If the User is not active (frozen account), log them in and display a banner message telling them to unfreeze their account
                # so that they can get back to earning money
                else:
                    pass
            # If no User object was returned, display an error message and send them to the
            # login page
            else:
                messages.add_message(request, messages.WARNING, 'The username or password you entered is incorrect. Please try again.')
                context = {'loginform': loginform}
                return render(request, 'splash/login.html', context)
        # If the form is not valid, display form errors and refresh the login form
        else:
            messages.add_message(request, messages.INFO, "In order to login, you must complete the form.")
            context = {'loginform': loginform}
            return render(request, 'splash/login.html', context)
    # If the form was not POSTed, refresh the login form and send them to the login page
    else:
        loginform = loginForm()
        context = {'loginform': loginform}
        return render(request, 'splash/login.html', context)

# View that handles logging out a User
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('splash:index'))

def trainerForHire(request):
    context = {}
    return render(request, 'splash/forhire.html', context)

templates/splash/base.html
{% extends 'index.html' %}
    {% load static from staticfiles %}

    {% block stylesheets %}
        <link href="{% static 'splash/css/style.css' %}" rel="stylesheet">
    {% endblock %}

    {% block mdfHeaderLinks %}
        <nav role="navigation" class="nav" id="mdfNav">
            <ul class="user-links">
                <li id="login"><a href="{% url 'splash:login' %}" class="link">log in</a></li>
                <li><a href="{% url 'splash:choice' %}" class="link">create account</a></li>
                <a href="{% url 'trainers:index' %}"><li class="mdfNavTrainerForHire" id="new">get hired</li></a>
            </ul>
        </nav>
    {% endblock %}

    {% block mdfContent %}
    <div class="splash" id="main">
        <div class="row" id="init">
            <div class="col-1-1 col-centered">
                <h1 class="white mdfSexyWeight text-center mdfSmallShadow">Hire an experienced personal trainer and get into the best shape of your life.</h1>
            </div>
        </div>
        <div class="row m-t-2">
            <div class="col-3-4 col-centered">
                {% if messages %}
                    <div class="row m-b-2">
                        <div class="col-1-1 col-centered text-center blue">
                            {% for message in messages %}
                                {{ message|linebreaks|escape }}
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}
                <form method="post" class="text-center" action="{% url 'splash:index' %}">
                    {% csrf_token %}
                    {% for field in new_form %}
                        {{ field }}
                    {% endfor %}
                    <button type="submit" class="signup-btn">search</button>
                </form>
                {% if new_form.searchQ.errors %}
                    {% for error in new_form.searchQ.errors %}
                        <p class="error">* {{ error|striptags|escape }}</p>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>

    <div class="row p-t-5 p-b-10">
        <div class="container">
            <div class="col-3-4 col-centered">
                <h1 class="mdfHeading text-center">Getting in shape just got a whole lot easier.</h1>
                <hr class="mdfHr">
            </div>
            <div class="row p-t-5">
                <div class="col-1-3 mdfFeatureBlockWrapper">
                    <img src="{% static 'splash/inc/plan.png' %}" class="mdfBlockImg" alt="Custom Plans">
                    <p class="mdfContent p-t-5 text-center">Receive personalized meal and workout plans from an experienced personal trainer.</p>
                </div>
                <div class="col-1-3 mdfFeatureBlockWrapper">
                    <img src="{% static 'splash/inc/track.png' %}" class="mdfBlockImg" alt="Custom Plans">
                    <p class="mdfContent p-t-5 text-center">Use our charting tools to track your progress and hone in on your weak areas to get the best results.</p>
                </div>
                <div class="col-1-3 mdfFeatureBlockWrapper">
                    <img src="{% static 'splash/inc/card.png' %}" class="mdfBlockImg" alt="Custom Plans">
                    <p class="mdfContent p-t-5 text-center">Pay your personal trainer securely through our industry standard payment processor.</p>
                </div>
            </div>
            <div class="row p-t-10">
                <div class="col-3-4 col-centered">
                    <h1 class="mdfHeading text-center">Real personal trainers. Real results.</h1>
                    <hr class="mdfHr">
                </div>
                <div class="row p-t-5">
                    <div class="col-1-3 mdfFeatureBlockWrapper">
                        <a href="#" class="mdfFeatureBlockWrapper" id="lose-weight">
                            <div class="mdfFeatureBlockContent">lose weight</div>
                            <div class="mdfFeatureBlock mdfFeature-lose-weight"></div>
                        </a>
                    </div>
                    <div class="col-1-3 mdfFeatureBlockWrapper">
                        <a href="#" class="mdfFeatureBlockWrapper" id="gain-muscle">
                            <div class="mdfFeatureBlockContent">gain muscle</div>
                            <div class="mdfFeatureBlock mdfFeature-gain-muscle"></div>
                        </a>
                    </div>
                    <div class="col-1-3 mdfFeatureBlockWrapper">
                        <a href="#" class="mdfFeatureBlockWrapper" id="cont-prep">
                            <div class="mdfFeatureBlockContent">get healthy</div>
                            <div class="mdfFeatureBlock mdfFeature-cont-prep"></div>
                        </a>
                    </div>
                </div>
            </div>
            <div class="row mdfCtaWrapper">
                <div class="col-3-4 col-centered">
                    <a href="#" class="mdfCtaContainer"><h4 class="trainerForHire mdfFrontCta">browse personal trainers</h4></a>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

{% block javascript %}
    <script src="{% static 'splash/js/jquery.js' %}"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/jquery-ui.min.js"></script>
    <script src="{% static 'skeleton/skeleton.js' %}"></script>
    <script src="{% static 'splash/js/splash.js' %}"></script>
{% endblock %}

templates/splash/interrupt.html
{% extends 'index.html' %}
    {% load static from staticfiles %}

    {% block title %}mydailyfit | create an account{% endblock %}

    {% block stylesheets %}
        <link href="{% static 'splash/css/style.css' %}" rel="stylesheet">
    {% endblock %}

    {% block mdfHeaderLinks %}
        <nav role="navigation" class="nav" id="mdfNav">
            <ul class="user-links">
                <li id="login"><a href="{% url 'splash:login' %}" class="link">log in</a></li>
                <li><a href="{% url 'splash:choice' %}" class="link">create account</a></li>
                <a href="{% url 'trainers:index' %}"><li class="mdfNavTrainerForHire" id="new">get hired</li></a>
            </ul>
        </nav>
    {% endblock %}

    {% block mdfContent %}
        <div class="row p-t-5 p-b-5">
            <h1 class="text-center m-b-5">Let's get you started on the right path!</h1>
            <div class="col-1-2" id="fit">
               <div class="col-1-2 col-centered" id="fitbrief">
                   <a href="{% url 'clients:signup' %}" class="mdfChooseYourFateBlueBtn text-center no-decor">I want to get fit</a>
                   <h4 class="m-t-5 mdfSexyWeight">Get customized meal and workout plans</h4>
                   <h4 class="m-t-2 mdfSexyWeight">Track your progress</h4>
                   <h4 class="m-t-2 m-b-2 mdfSexyWeight">Begin your journey towards a healthier life</h4>
                   <a href="#" class="mdfLink">learn more</a>
               </div>
            </div>
            <div class="col-1-2" id="train">
               <div class="col-1-2 col-centered" id="trainbrief">
                   <a href="{% url 'trainers:signup' %}" class="mdfChooseYourFateBtn text-center no-decor">I want to train people</a>
                   <h4 class="m-t-5 mdfSexyWeight">Find more people to train</h4>
                   <h4 class="m-t-2 mdfSexyWeight">Earn money online</h4>
                   <h4 class="m-t-2 m-b-2 mdfSexyWeight">Grow your personal training career</h4>
                   <a href="{% url 'trainers:index' %}" class="mdfLink">learn more</a>
               </div>
            </div>
        </div>
    {% endblock %}

    {% block javascript %}
        <script src="{% static 'splash/js/jquery.js' %}"></script>
        <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/jquery-ui.min.js"></script>
        <script src="{% static 'skeleton/skeleton.js' %}"></script>
        <script src="{% static 'splash/js/splash.js' %}"></script>
    {% endblock %}

templates/splash/login.html
{% extends 'index.html' %}
{% load static from staticfiles %}

    {% block stylesheets %}
        <link href="{% static 'skeleton/skeleton.css' %}" rel="stylesheet">
        <link href="{% static 'trainers/css/style.css' %}" rel="stylesheet">
    {% endblock %}

    {% block mdfHeaderLinks %}
        <nav role="navigation" class="nav" id="mdfNav">
            <ul class="user-links">
                <li class="blue text-center">don't have an account?</li>
                <li><a href="{% url 'splash:choice' %}" class="text-center link no-decor">create account</a></li>
                <a href="{% url 'trainers:signup' %}"><li class="mdfNavTrainerForHire" id="new">get hired</li></a>
            </ul>
        </nav>
    {% endblock %}

    {% block mdfContent %}
    <div class="row" id="mdfLogin">
        <div class="container">
            <div class="col-1-2 col-centered">
                <h1 class="mdfSexyWeight m-b-2 white text-center">Get back to it!</h1>
                <hr class="mdfHr">
            </div>
            <div class="col-1-2 p-t-2 col-centered">
                {% if messages %}
                    {% for message in messages %}
                        <p class="error text-center">{{ message }}</p>
                    {% endfor %}
                {% endif %}
                {% for field in loginform %}
                    {% for error in field.errors %}
                        <p class="error text-center">{{ field.label|title }} {{ error }}</p>
                    {% endfor %}
                {% endfor %}
                <form action="{% url 'splash:login' %}" id="login-form" method="post" class="text-center">
                    {% csrf_token %}
                    {% for field in loginform %}
                        {{ field }}
                    {% endfor %}
                    <button type="submit" class="mdfLogInBtn">Log In</button>
                </form>
            </div>
        </div>
    </div>
    {% endblock %}

{% block javascript %}
    <script src="{% static 'splash/js/jquery.js' %}"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/jquery-ui.min.js"></script>
    <script src="{% static 'skeleton/mask.js' %}"></script>
    <script src="{% static 'skeleton/skeleton.js' %}"></script>
    <script src="{% static 'trainers/js/trainers.js' %}"></script>
{% endblock %}