clients/urls.py
from django.conf.urls import patterns, url
from django.conf import settings
from django.conf.urls.static import static

from clients import views

urlpatterns = patterns('',
	url(r'^signup/$', views.new_client, name='signup'),
	url(r'^(?P<username>\w+)/$', views.client_account, name='account'),
	url(r'^(?P<username>\w+)/settings/$', views.client_settings, name='settings'),
	url(r'^(?P<username>\w+)/settings/del-goal/(?P<goal_id>[0-9]+)/$', views.delete_goal, name='del_goal'),
	url(r'^(?P<username>\w+)/settings/del-prof-pic/$', views.delete_profile_pic, name='del_prof_pic'),
	url(r'^(?P<username>\w+)/settings/del-ban-img/$', views.delete_banner_img, name='del_ban_img'),
)

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mdfMessaging/urls.py
from django.conf.urls import patterns, url
from django.conf import settings
from django.conf.urls.static import static

from mdfMessaging import views

urlpatterns = patterns('',
     url(r'^(?P<username>\w+)/$', views.messageList, name='message_list'),
     url(r'^(?P<username>\w+)/message/(?P<message_id>\d+)/$', views.messageDetail, name='message_detail'),
     url(r'^(?P<username>\w+)/message/(?P<message_id>\d+)/delete/$', views.send_to_trash, name='delete_message'),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mydailyfit/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	url(r'^admin/', include(admin.site.urls)),
	url(r'^', include('splash.urls', namespace='splash')),
	url(r'^trainers/', include('trainers.urls', namespace='trainers')),
	url(r'^client/', include('clients.urls', namespace='clients')),
	url(r'^messages/', include('mdfMessaging.urls', namespace='messages')),
	url(r'^plans/', include('fitplans.urls', namespace='fitplans')),
)

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

splash/urls.py
from django.conf.urls import patterns, url
from django.conf import settings
from django.conf.urls.static import static

from splash import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^decisions/$', views.make_good_choices, name='choice'),
    #url(r'^trainersplash/$', views.trainerForHire, name='trainersplash'),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trainers/urls.py
from django.conf.urls import patterns, url
from django.conf import settings
from django.conf.urls.static import static

from trainers import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^(?P<username>\w+)/error/$', views.display_error_page, name='error'),
	url(r'^signup/$', views.new_trainer, name='signup'),
	url(r'^(?P<username>\w+)/$', views.trainer_account, name='account'),
	url(r'^(?P<username>\w+)/profile/$', views.trainer_profile, name='profile'),
	url(r'^(?P<username>\w+)/settings/$', views.trainer_settings, name='settings'),
	url(r'^(?P<username>\w+)/settings/auth-stripe/$', views.stripe_auth, name='auth_stripe'),
	url(r'^(?P<username>\w+)/settings/del-prof-pic/$', views.delete_profile_pic, name='del_prof_pic'),
	url(r'^(?P<username>\w+)/settings/del-ban-img/$', views.delete_banner_img, name='del_ban_img'),
	url(r'^(?P<username>\w+)/settings/del-specialty/(?P<specialty_id>[0-9]+)/$', views.delete_specialty, name='del_specialty'),
	url(r'^(?P<username>\w+)/delvideo/(?P<id>[0-9]+)/$', views.delete_video, name='delete_video'),
)

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mdfMessaging/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from django.contrib.auth.models import User

# Model that stores the messages
class PrivateMessage(models.Model):
    sender = models.CharField(_('Sent From'), max_length=30)
    sent_to = models.CharField(_('Sent To'), max_length=30)
    sent_date = models.DateField(auto_now_add=True)
    subject = models.CharField(_('Message Subject'), max_length=70)
    message = models.TextField(_('Message'))
    read_on = models.DateField(_('Date Read'), null=True, blank=True)
    replied_on = models.DateField(_('Date Replied'), null=True, blank=True)
    sender_deleted = models.BooleanField(default=False)
    recipient_deleted = models.BooleanField(default=False)

    def __unicode__(self):
        return self.subject

mdfMessaging/forms.py
from django import forms
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.utils.translation import ugettext_lazy as _

from mdfMessaging.models import PrivateMessage
from trainers.models import Trainer

my_default_errors = {
    'required': ' -\tThis field is required\n',
    'invalid': ' -\tPlease enter a valid value\n',
    'min_value': '-\tPlease enter a valid value\n',
    'max_value': '-\tPlease enter a valid value\n'
}

class composeMessage(forms.Form):
    recipient = forms.CharField(max_length=30, error_messages=my_default_errors,
                                widget=forms.TextInput(
                                    attrs={
                                        'placeholder': 'Send to',
                                        'class': 'signup-form-input m-b-1',
                                        'id': 'recipient'
                                    }
                                ))
    subject = forms.CharField(max_length=100, error_messages=my_default_errors,
                              widget=forms.TextInput(
                                  attrs={
                                      'placeholder': 'Message Subject',
                                      'class': 'signup-form-input m-b-1',
                                      'id': 'subject'
                                  }
                              ))
    message = forms.CharField(error_messages=my_default_errors,
                              widget=forms.Textarea(
                                  attrs={
                                      'placeholder': 'Write a message',
                                      'class': 'signup-form-input',
                                      'id': 'message'
                                  }
                              ))

    def create_message(self, sender):
        recipient = self.cleaned_data['recipient']
        subject = self.cleaned_data['subject']
        message = self.cleaned_data['message']
        new_message = PrivateMessage.objects.create(sender=sender, sent_to=recipient, subject=subject, message=message)
        new_message.save()

mdfMessaging/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponseRedirect,redirect
from django.contrib import messages
from django.core.urlresolvers import reverse
from datetime import datetime
from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User
from trainers.models import Trainer,Trainee
from clients.models import Client
from mdfMessaging.models import PrivateMessage

from mdfMessaging.forms import composeMessage


@login_required(login_url='/login')
def messageList(request,username):
	if not request.user.is_authenticated():
		return redirect(reverse('splash:login'))
	try:
		user=User.objects.get(username=username)
		context={}
	except User.DoesNotExist:
		return redirect(reverse('splash:login'))

	if request.user!=user:
		return redirect(reverse('splash:login'))

	try:
		trainer=Trainer.objects.get(user=user)
		is_trainer=True
		trainees=Trainee.objects.all().filter(trainer=trainer)
		context['trainer']=trainer
		context['trainees']=trainees
	except Trainer.DoesNotExist:
		is_trainer=False

	try:
		client=Client.objects.get(user=user)
		context['client']=client
		try:
			client_trainer = Trainee.objects.get(client=client)
			my_trainer = client_trainer.trainer
			context['my_trainer'] = my_trainer
		except Trainee.DoesNotExist:
			pass
	except Client.DoesNotExist:
		pass

	composeForm=composeMessage()
	inbox=PrivateMessage.objects.filter(sent_to=user,recipient_deleted=False).order_by('-sent_date')
	sent=PrivateMessage.objects.filter(sender=user,sender_deleted=False).order_by('-sent_date')

	if request.method=='POST':
		composeForm=composeMessage(request.POST)
		if composeForm.is_valid():
			composeForm.create_message(user.username)
			messages.add_message(request,messages.SUCCESS,"You're message has been sent successfully.")
			return HttpResponseRedirect(reverse('messages:trainer_messages',args=(user.username,)))

	context={'user':user,'inbox':inbox,'sent':sent,'form':composeForm,'isTrainer':is_trainer,}
	return render(request,'mdfMessaging/messages.html',context)


'''
This function used to return a Client's messages.

Need to create Client app before uncommenting this view.

@login_required(login_url='login')
def clientMessages(request, username):
    if not request.user.is_authenticated():
        return redirect(reverse('splash:login'))
    user = get_object_or_404(User, username=username)
    if request.user != user:
        return redirect(reverse('splash:login'))
    client = get_object_or_404(Client, user=user)
    inbox = PrivateMessage.objects.filter(sent_to=client)
    sent = PrivateMessage.objects.filter(sender=client)
    context = {'user': user, 'client': client, 'inbox': inbox, 'sent': sent}
    return render(request, 'clients/messages.html', context)

'''


@login_required(login_url='/login')
def messageDetail(request,username,message_id):
	if not request.user.is_authenticated():
		return redirect(reverse('splash:login'))
	try:
		user=User.objects.get(username=username)
	except User.DoesNotExist:
		return redirect(reverse('splash:login'))
	if request.user!=user:
		return redirect(reverse('splash:login'))

	try:
		trainer=Trainer.objects.get(user=user)
		is_trainer=True
	except Trainer.DoesNotExist:
		is_trainer=False

	message=PrivateMessage.objects.get(pk=message_id)
	if message.read_on==None:
		message.read_on=datetime.now()
		message.save()

	composeForm=composeMessage(initial={'recipient':message.sender,'subject':'RE: '+message.subject})

	if request.method=='POST':
		composeForm=composeMessage(request.POST)
		if composeForm.is_valid():
			composeForm.create_message(user.username)
			message.replied_on=datetime.now()
			message.save()
			messages.add_message(request,messages.SUCCESS,"You're message has been sent successfully.")
			return HttpResponseRedirect(reverse('messages:trainer_messages',args=(user.username,)))

	context={'user':user,'trainer':trainer,'message':message,'form':composeForm,'isTrainer':is_trainer}
	return render(request,'mdfMessaging/message.html',context)


@login_required(login_url='/login')
def send_to_trash(request,username,message_id):
	if not request.user.is_authenticated():
		return redirect(reverse('splash:login'))

	message=PrivateMessage.objects.get(pk=message_id)

	if message.sender==username:
		message.sender_deleted=True
		message.save()
	elif message.sent_to==username:
		message.recipient_deleted=True
		message.save()

	if message.recipient_deleted==True and message.sender_deleted==True:
		message.delete()

	return HttpResponseRedirect(reverse('messages:trainer_messages',args=(username,)))

templates/mdfMessaging/message.html
{% extends 'index.html' %}
    {% load static from staticfiles %}

    {% block title %}mydailyfit | {{ message.subject }}{% endblock %}

    {% block stylesheets %}
        <link href="{% static 'skeleton/skeleton.css' %}" rel="stylesheet">
        <link href="{% static 'mdfMessaging/css/style.css' %}" rel="stylesheet">
    {% endblock %}

    {% block mdfHeaderLinks %}
        <nav role="navigation" class="nav" id="mdfNav">
            <ul class="user-links">
                <li><a href="{% url 'trainers:account' user.username %}" class="link">dashboard</a></li>
                {% if isTrainer %}
                    <li><a href="{% url 'trainers:profile' user.username %}" class="link">profile</a></li>
                {% else %}
                    <li><a href="#" class="link">profile</a></li>
                {% endif %}
                <li><a href="#" class="link">activity</a></li>
                <li><a href="{% url 'messages:message_list' user.username %}" class="active">messages</a></li>
                <li><a href="{% url 'trainers:settings' user.username %}" class="link">settings</a></li>
                <li><a href="{% url 'splash:logout' %}" class="link">logout</a></li>
            </ul>
        </nav>
    {% endblock %}

    {% block mdfContent %}
        <div class="row p-t-5 p-b-5 mdfClickContainer" id="message">
            <div class="col-3-4 col-centered mdfMessageDetail">
                <h2 class="mdfMessageSubject">{{ message.subject }}</h2>
                <div class="mdfMessageDates">
                    <p class="mdfMessageSentDate">Sent <span class="blue">{{ message.sent_date }}</span></p>
                    {% if not message.sender == user.username %}
                        <p class="mdfMessageReadDate">Read <span class="blue">{{ message.read_on }}</span></p>
                    {% endif %}
                </div>
                {% if message.sender == user.username %}
                    <p class="p-b-2 mdfMessageSender">To: <a href="#" class="mdfLink">{{ message.sent_to }}</a></p>
                {% else %}
                    <p class="p-b-2 mdfMessageSender">From: <a href="#" class="mdfLink">{{ message.sender }}</a></p>
                {% endif %}
                <h3 class="p-t-2 mdfMessageDetailContent">{{ message.message|linebreaksbr }}</h3>
                <a href="{% url 'messages:delete_message' user.username message.id %}" class="mdfMessageDelete text-center no-decor">Delete</a>
                {% if not message.sender == user.username %}
                    <a href="" class="mdfClickToShow mdfLink text-center mdfReplyBtn" data-target="message-reply">Reply</a>
                {% endif %}
            </div>
        </div>
        <div class="col-3-4 m-t-5 m-b-5 col-centered mdfClickContainer" id="message-reply">
                <div class="row">
                    <div class="col-1-4">
                        <h4><a href="" class="mdfClickToShow text-center no-decor mdfLogInBtn" id="view-message" data-target="message">view message</a></h4>
                    </div>
                </div>
                <h1 class="text-center m-b-2 blue">New Message</h1>
                <form action="#" method="post" class="text-center">
                    {% csrf_token %}
                    <div class="mdfInputLabel">
                        <h4>Send Message to:</h4>
                        {{ form.recipient }}
                    </div>
                    <div class="mdfInputLabel">
                        <h4>Message Subject:</h4>
                        {{ form.subject }}
                    </div>
                    <div class="mdfInputLabel">
                        <h4>Message:</h4>
                        {{ form.message }}
                    </div>
                    <input type="submit" class="mdfLogInBtn" value="Send Message">
                </form>
            </div>
    {% endblock %}

    {% block javascript %}
        <script src="{% static 'splash/js/jquery.js' %}"></script>
        <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/jquery-ui.min.js"></script>
        <script src="{% static 'skeleton/skeleton.js' %}"></script>
        <script src="{% static 'mdfMessaging/js/messages.js' %}"></script>
    {% endblock %}

templates/mdfMessaging/messages.html
{% extends 'index.html' %}
    {% load static from staticfiles %}

    {% block title %}mydailyfit | messages{% endblock %}

    {% block stylesheets %}
        <link href="{% static 'skeleton/skeleton.css' %}" rel="stylesheet">
        <link href="{% static 'mdfMessaging/css/style.css' %}" rel="stylesheet">
    {% endblock %}

    {% block mdfHeaderLinks %}
        <nav role="navigation" class="nav" id="mdfNav">
            <ul class="user-links">
                <li><a href="{% url 'trainers:account' user.username %}" class="link">dashboard</a></li>
                {% if isTrainer %}
                    <li><a href="{% url 'trainers:profile' user.username %}" class="link">profile</a></li>
                {% else %}
                    <li><a href="#" class="link">profile</a></li>
                {% endif %}
                <li><a href="#" class="link">activity</a></li>
                <li><a href="{% url 'messages:message_list' user.username %}" class="active">messages</a></li>
                <li><a href="{% url 'trainers:settings' user.username %}" class="link">settings</a></li>
                <li><a href="{% url 'splash:logout' %}" class="link">logout</a></li>
            </ul>
        </nav>
    {% endblock %}

    {% block mdfContent %}
        <div class="row p-t-5 p-b-5">
            <div class="col-3-4 col-centered" id="messages-container">
                <div class="col-1-5" id="message-tabs">
                    <a href="" class="m-b-5 mdfLogInBtn no-decor text-center mdfClickToShow" data-target="compose-message" id="new-message">new message</a></h3>
                    <h3 class="mdfSexyWeight m-b-5"><a href="" class="active mdfClickToShow" data-target="inbox-messages" id="inbox">Inbox</a></h3>
                    <h3 class="mdfSexyWeight m-b-5"><a href="" class="mdfLink mdfClickToShow" data-target="sent-messages" id="sent">Sent</a></h3>
                    {% if not isTrainer %}
                        <h3 class="mdfSexyWeight"><a href="" class="mdfLink mdfClickToShow" data-target="connection-list" id="connections">My Trainers</a></h3>
                    {% else %}
                        <h3 class="mdfSexyWeight"><a href="" class="mdfLink mdfClickToShow" data-target="client-list" id="clients">My Clients</a></h3>
                    {% endif %}
                </div>
                <div class="col-4-5 mdfClickContainer" id="inbox-messages">
                    {% if messages %}
                        {% for success in messages %}
                            <h3 class="text-center green mdfSexyWeight" id="success">{{ success }}</h3>
                        {% endfor %}
                    {% endif %}
                    {% if inbox %}
                        {% for message in inbox %}
                            <a href="{% url 'messages:message_detail' user.username message.pk %}" class="no-decor mdfMessageLink">
                                <div class="mdfMessage">
                                    <h2 class="mdfMessageSubject">{{ message.subject }}</h2>
                                    <div class="mdfMessageDates">
                                        <p class="mdfMessageSentDate">Received <span class="blue">{{ message.sent_date }}</span></p>
                                        {% if message.read_on %}
                                            <p class="mdfMessageReadDate">Read <span class="blue">{{ message.read_on }}</span></p>
                                        {% endif %}
                                        {% if message.replied_on %}
                                            <p class="mdfMessageReadDate">Replied <span class="blue">{{ message.replied_on }}</span></p>
                                        {% endif %}
                                    </div>
                                    <h4 class="mdfMessageSender">Sent from <span class="blue">{{ message.sender }}</span></h4>
                                    <p class="mdfMessageSnippet">{{ message.message|truncatewords:25 }}</p>
                                </div>
                            </a>
                        {% endfor %}
                    {% else %}
                        <h3 class="m-l-2 p-t-5 p-b-5 mdfSexyWeight">You don't have any messages.</h3>
                    {% endif %}
                </div>
                <div class="col-4-5 mdfClickContainer" id="sent-messages">
                    {% if sent %}
                        {% for message in sent %}
                            <a href="{% url 'messages:message_detail' user.username message.pk %}" class="no-decor mdfMessageLink">
                                <div class="mdfMessage">
                                    <h3 class="mdfMessageSubject">{{ message.subject }}</h3>
                                    <div class="mdfMessageDates">
                                        <p class="mdfMessageSentDate">Sent <span class="blue">{{ message.sent_date }}</span></p>
                                    </div>
                                    <h4 class="mdfMessageSender">Sent to <span class="blue">{{ message.sent_to }}</span></h4>
                                    <p class="mdfMessageSnippet">{{ message.message|truncatewords:25 }}</p>
                                </div>
                            </a>
                        {% endfor %}
                    {% else %}
                        <h3 class="m-l-2 p-t-5 p-b-5 mdfSexyWeight">You haven't sent any messages.</h3>
                    {% endif %}
                </div>
                <div class="col-4-5 mdfClickContainer" id="client-list">
                    {% if trainees %}
                        {% for trainee in trainees %}
                            <div class="row">
                                <h4 class="mdfSexyWeight m-t-2 m-b-2">{{ user.username }}</h4>
                            </div>
                        {% endfor %}
                    {% else %}
                        <h3 class="m-l-2 p-t-5 p-b-5 mdfSexyWeight">You have no clients.</h3>
                        <div class="row">
                            <h4 class="m-l-2 mdfSexyWeight m-t-2 m-b-2"><a href="#" class="mdfLink">{{ user.first_name|title }} {{ user.last_name|title }}</a></h4>
                        </div>
                    {% endif %}
                </div>
                <div class="col-4-5 mdfClickContainer" id="connection-list">
                    {% if my_trainer %}
                        <div class="row">
                            <h4 class="mdfSexyWeight m-t-2 m-b-2">{{ my_trainer }}</h4>
                        </div>
                    {% else %}
                        <div class="row">
                            <h3 class="mdfSexyWeight m-l-2 p-t-5 p-b-5">You have no trainers</h3>
                        </div>
                    {% endif %}
                </div>
                <div class="col-4-5 p-l-2 mdfClickContainer" id="compose-message">
                    <form action="#" method="post" class="m-l-2">
                        {% csrf_token %}
                        <div class="mdfInputLabel">
                            <h4>Send Message to:</h4>
                            {{ form.recipient }}
                        </div>
                        <div class="mdfInputLabel">
                            <h4>Message Subject:</h4>
                            {{ form.subject }}
                        </div>
                        <div class="mdfInputLabel">
                            <h4>Message:</h4>
                            {{ form.message }}
                        </div>
                        <input type="submit" class="mdfLogInBtn" value="Send Message">
                    </form>
                </div>
            </div>
        </div>
    {% endblock %}


    {% block javascript %}
        <script src="{% static 'splash/js/jquery.js' %}"></script>
        <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/jquery-ui.min.js"></script>
        <script src="{% static 'skeleton/skeleton.js' %}"></script>
        <script src="{% static 'mdfMessaging/js/messages.js' %}"></script>
    {% endblock %}