clients/urls.py
from django.conf.urls import patterns, url
from django.conf import settings
from django.conf.urls.static import static

from clients import views

urlpatterns = patterns('',
	url(r'^signup/$', views.new_client, name='signup'),
	url(r'^(?P<username>\w+)/$', views.client_account, name='account'),
	url(r'^(?P<username>\w+)/settings/$', views.client_settings, name='settings'),
	url(r'^(?P<username>\w+)/settings/del-goal/(?P<goal_id>[0-9]+)/$', views.delete_goal, name='del_goal'),
	url(r'^(?P<username>\w+)/settings/del-prof-pic/$', views.delete_profile_pic, name='del_prof_pic'),
	url(r'^(?P<username>\w+)/settings/del-ban-img/$', views.delete_banner_img, name='del_ban_img'),
)

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mdfMessaging/urls.py
from django.conf.urls import patterns, url
from django.conf import settings
from django.conf.urls.static import static

from mdfMessaging import views

urlpatterns = patterns('',
     url(r'^(?P<username>\w+)/$', views.messageList, name='message_list'),
     url(r'^(?P<username>\w+)/message/(?P<message_id>\d+)/$', views.messageDetail, name='message_detail'),
     url(r'^(?P<username>\w+)/message/(?P<message_id>\d+)/delete/$', views.send_to_trash, name='delete_message'),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mydailyfit/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	url(r'^admin/', include(admin.site.urls)),
	url(r'^', include('splash.urls', namespace='splash')),
	url(r'^trainers/', include('trainers.urls', namespace='trainers')),
	url(r'^client/', include('clients.urls', namespace='clients')),
	url(r'^messages/', include('mdfMessaging.urls', namespace='messages')),
	url(r'^plans/', include('fitplans.urls', namespace='fitplans')),
)

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

splash/urls.py
from django.conf.urls import patterns, url
from django.conf import settings
from django.conf.urls.static import static

from splash import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^decisions/$', views.make_good_choices, name='choice'),
    #url(r'^trainersplash/$', views.trainerForHire, name='trainersplash'),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trainers/urls.py
from django.conf.urls import patterns, url
from django.conf import settings
from django.conf.urls.static import static

from trainers import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^(?P<username>\w+)/error/$', views.display_error_page, name='error'),
	url(r'^signup/$', views.new_trainer, name='signup'),
	url(r'^(?P<username>\w+)/$', views.trainer_account, name='account'),
	url(r'^(?P<username>\w+)/profile/$', views.trainer_profile, name='profile'),
	url(r'^(?P<username>\w+)/settings/$', views.trainer_settings, name='settings'),
	url(r'^(?P<username>\w+)/settings/auth-stripe/$', views.stripe_auth, name='auth_stripe'),
	url(r'^(?P<username>\w+)/settings/del-prof-pic/$', views.delete_profile_pic, name='del_prof_pic'),
	url(r'^(?P<username>\w+)/settings/del-ban-img/$', views.delete_banner_img, name='del_ban_img'),
	url(r'^(?P<username>\w+)/settings/del-specialty/(?P<specialty_id>[0-9]+)/$', views.delete_specialty, name='del_specialty'),
	url(r'^(?P<username>\w+)/delvideo/(?P<id>[0-9]+)/$', views.delete_video, name='delete_video'),
)

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clients/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.shortcuts import render_to_response

import os

from django.contrib.auth.models import User

from trainers.utils import get_image_path

class Client(models.Model):
	user = models.ForeignKey(User)
	description = models.TextField(_('About'), blank=True)
	location = models.CharField(_('Location'), max_length=150, default='', blank=True)
	height_ft = models.PositiveIntegerField(_('Feet'), blank=True, null=True)
	height_in = models.PositiveIntegerField(_('Inches'), blank=True, null=True)
	weight_before = models.PositiveIntegerField(_('Weight in Pounds'), blank=True, null=True)
	weight_after = models.PositiveIntegerField(_('Weight in Pounds'), blank=True, null=True)
	body_fat_before = models.PositiveIntegerField(_('Body Fat Percentage'), blank=True, null=True)
	body_fat_after = models.PositiveIntegerField(_('Body Fat Percentage'), blank=True, null=True)
	before_img = models.FileField(_('Before Picture'), upload_to=get_image_path, blank=True, null=True)
	after_img = models.FileField(_('After Picture'), upload_to=get_image_path, blank=True, null=True)
	profile_img = models.FileField(_('Profile Picture'), upload_to=get_image_path, blank=True, null=True)
	banner_img = models.FileField(_('Banner picture'), upload_to=get_image_path, blank=True, null=True)
	last_online = models.DateField(_('Client Last Online On'), blank=True, null=True)
	mealplan_id = models.IntegerField(null=True)
	workoutplan_id = models.IntegerField(null=True)

	def photo_name(self):
		return os.path.basename(self.profile_img.name)

	def banner_photo_name(self):
		return os.path.basename(self.banner_img.name)

	def __unicode__(self):
		return self.user.username

class Goal(models.Model):
	client = models.ForeignKey(Client)
	goal = models.CharField(_('Goal'), max_length=255, default='', blank=True, null=True)
	before = models.CharField(_('Goal Before'), max_length=255, default='', blank=True, null=True)
	after = models.CharField(_('Goal After'), max_length=255, default='', blank=True, null=True)

	def get_updates(self):
		updates = GoalUpdate.objects.all().filter(goal=self)
		return render_to_response('clients/updates.html', {'updates': updates}, content_type="application/xhtml+xml")

	def __unicode__(self):
		return self.goal

class GoalUpdate(models.Model):
	goal = models.ForeignKey(Goal)
	up = models.PositiveIntegerField(_('Increased by'), default=0, blank=True, null=True)
	down = models.PositiveIntegerField(_('Decreased by'), default=0, blank=True, null=True)
	update = models.CharField(_('Progress'), max_length=255, default='', blank=True, null=True)
	updated_on = models.DateField(_('Updated On'), auto_now=True)

	def __unicode__(self):
		return self.update

clients/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from django.core.exceptions import ValidationError

from clients.forms import newClient, clientSettings, goalForm, updateGoalForm

from django.contrib.auth.models import User
from clients.models import Client, Goal, GoalUpdate
from trainers.models import Trainee

# This function is used to create a new User object if the
# form that was submitted is valid
def new_client(request):
	new_client = newClient()
	# Make sure the form was POSTed
	if request.method == 'POST':
		new_client = newClient(request.POST)
		if new_client.is_valid():
			username = request.POST['username']
			password = request.POST['password']
			# Grab the user's input and check it against current User objects in database
			# If an inputted value is already stored in the database, raise a ValidationError
			if new_client.check_email() and new_client.check_username():
			# If both checks pass, create the new User
				new_client.create_new_user()
				user = authenticate(username=username, password=password)
				if user is not None:
					login(request, user)
					return HttpResponseRedirect(reverse('clients:account', args=[username]))
			# If the check fails, display an error message
			elif not new_client.check_email():
				messages.add_message(request, messages.WARNING, 'The e-mail you entered is already associated with an account on file.')
			elif not new_client.check_username():
				messages.add_message(request, messages.WARNING, 'The username you entered is already associated with an account on file.')
	context = {'newclient': new_client}
	return render(request, 'clients/signup.html', context)

@login_required(login_url='/login')
def client_account(request, username):
	# If the user accessing the page isn't authorized
	# redirect to login page
	if not request.user.is_authenticated():
		return HttpResponseRedirect(reverse('splash:login'))

	# Try to grab the associated User object
	try:
		user = User.objects.get(username=username)
	# If no User matches the query
	# redirect to login page
	except User.DoesNotExist:
		return HttpResponseRedirect(reverse('splash:login'))

	# If the user's don't match
	# redirect to login page
	if request.user != user:
		return HttpResponseRedirect(reverse('splash:login'))

	# Try to grab the Client object associated with the current User
	try:
		client = Client.objects.get(user=user)
		context = {'client': client, 'user': user}

		# Check if this Client has hired a Personal Trainer
		try:
			trainee = Trainee.objects.get(client=client)
			context += {'trainee': trainee}
		except Trainee.DoesNotExist:
			pass

	# Redirect if a Client for the associated User doesn't exist
	except Client.DoesNotExist:
		return HttpResponseRedirect(reverse('splash:login'))

	return render(request, 'clients/dashboard.html', context)

@login_required(login_url='/login')
def client_settings(request, username):
	if not request.user.is_authenticated():
		return HttpResponseRedirect(reverse('splash:login'))
	# Try to grab the associated User object
	try:
		user = User.objects.get(username=username)
	# If no User matches the query, redirect to login page
	except User.DoesNotExist:
		return HttpResponseRedirect(reverse('splash:login'))

	# If the user's don't match, redirect to login page
	if request.user != user:
		return HttpResponseRedirect(reverse('splash:login'))

	# Get the associated Client object
	try:
		client = Client.objects.get(user=user)
		settingsForm = clientSettings()
		addGoal = goalForm()
		updateGoal = updateGoalForm()
		context = {'client': client, 'user': user, 'settingsForm': settingsForm, 'goalForm': addGoal, 'updateGoal': updateGoal}

		try:
			goals = Goal.objects.all().filter(client=client)
			goals_count = goals.count()
			context['goals_count'] = range(goals_count)
			context['goals'] = goals
			for goal in goals:
				try:
					updates = GoalUpdate.objects.all().filter(goal=goal)
					context['updates'] = updates
					count = 0
					for update in updates:
						context[str(count)] = update
						count = count + 1
				except GoalUpdate.DoesNotExist:
					pass
		except Goal.DoesNotExist:
			pass

		if request.method == 'POST':
			if 'mdfSaveClientSettings' in request.POST:
				settingsForm = clientSettings(request.POST, request.FILES)
				if settingsForm.is_valid():
					settingsForm.save_changes(username)
				else:
					messages.add_message(request, messages.ERROR, settingsForm.errors)
					return HttpResponseRedirect(reverse('clients:settings', args=(username,)))
			if 'mdfAddGoal' in request.POST:
				addGoal = goalForm(request.POST)
				if addGoal.is_valid():
					addGoal.new_goal(username)
			if 'mdfUpdateGoal' in request.POST:
				updateGoal = updateGoalForm(request.POST)
				if updateGoal.is_valid():
					goal_id = request.POST['goal_id']
					updateGoal.update_goal(username, goal_id)
				else:
					return HttpResponseRedirect(reverse('clients:account', args=(username,)))
	except Client.DoesNotExist:
		return HttpResponseRedirect(reverse('splash:login'))

	return render(request, 'clients/settings.html', context)

def delete_profile_pic(request, username):
	if not request.user.is_authenticated():
		return HttpResponseRedirect(reverse('splash:login'))

	try:
		user = User.objects.get(username=username)
		if request.user != user:
			return HttpResponseRedirect(reverse('splash:login'))
	except User.DoesNotExist:
		return HttpResponseRedirect(reverse('splash:login'))

	try:
		client = Client.objects.get(user=user)
		client.profile_img.delete()
		client.save()
		return HttpResponseRedirect(reverse('trainers:account', args=(username,)))
	except Client.DoesNotExist:
		return HttpResponseRedirect(reverse('splash:login'))


def delete_banner_img(request, username):
	if not request.user.is_authenticated():
		return HttpResponseRedirect(reverse('splash:login'))

	try:
		user = User.objects.get(username=username)
		if request.user != user:
			return HttpResponseRedirect(reverse('splash:login'))
	except User.DoesNotExist:
		return HttpResponseRedirect(reverse('splash:login'))

	try:
		client = Client.objects.get(user=user)
		client.banner_img.delete()
		client.save()
		return HttpResponseRedirect(reverse('trainers:account', args=(username,)))
	except Client.DoesNotExist:
		return HttpResponseRedirect(reverse('splash:login'))

def delete_goal(request, username, goal_id):
	if not request.user.is_authenticated():
		return HttpResponseRedirect(reverse('splash:login'))

	try:
		user = User.objects.get(username=username)
		if request.user != user:
			return HttpResponseRedirect(reverse('splash:login'))
	except User.DoesNotExist:
		return HttpResponseRedirect(reverse('splash:login'))

	try:
		client = Client.objects.get(user=user)
		goal = Goal.objects.all().filter(client=client, pk=goal_id)
		goal.delete()
		return HttpResponseRedirect(reverse('clients:settings', args=(username,)))
	except Client.DoesNotExist:
		return HttpResponseRedirect(reverse('splash:login'))

templates/clients/settings.html
{% extends 'index.html' %}
    {% load static from staticfiles %}
        {% load clients_extras %}

    {% block title %}{{ user.first_name }} {{ user.last_name }} | settings{% endblock %}

    {% block stylesheets %}
    <link href="{% static 'skeleton/skeleton.css' %}" rel="stylesheet">
    <link href="{% static 'trainers/css/style.css' %}" rel="stylesheet">
    {% endblock %}

    {% block mdfHeaderLinks %}
        <nav role="navigation" class="nav" id="mdfNav">
            <ul class="user-links">
                <li><a href="{% url 'clients:account' user.username %}" class="link">dashboard</a></li>
                <li><a href="{% url 'trainers:profile' user.username %}" class="link">profile</a></li>
                <li><a href="{% url 'messages:message_list' user.username %}" class="link">messages</a></li>
                <li><a href="{% url 'clients:settings' user.username %}" class="active">settings</a></li>
                <li><a href="{% url 'splash:logout' %}" class="link">logout</a></li>
            </ul>
        </nav>
    {% endblock %}

    {% block mdfContent %}
        <div class="row">
            <div {% if not client.banner_img %} style="background: linear-gradient(to bottom, #666, #333);" {% elif client.banner_img %}
                                            style="background: url('{{ client.banner_img.url }}') center; background-size: cover;" {% endif %}>
                <div class="overlay p-t-8 p-b-8">
                    <div class="row">
                        <div class="col-1-3 col-centered" id="user-info">
                            <div class="mdfProfilePic" {% if not client.profile_img %} style="background: url('{% static 'trainers/inc/icon.jpg' %}'); background-size: cover;" {% elif client.profile_img %}
                                                style="background: url('{{ client.profile_img.url }}') center; background-size: cover;" {% endif %}></div>
                        </div>
                        <div class="col-1-3 col">
                            <h1 class="mdfUserDeets logoscript">{{ user.first_name|title }} {{ user.last_name|title }}</h1>
                            <h1 class="mdfUserDeets">{{ client.location }}</h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="dashboard">
            <div class="row dashboard-col" id="mdfSettingsLinks">
                <div id="mdfDashCollapse">
                    <p>DASHBOARD MENU</p>
                </div>
                <div id="mdfDashLinkContainer">
                    <div class="row">
                        <h4><a href="#settings" class="active mdfClickToShow" data-target="settings" id="settingslink">settings</a></h4>
                    </div>
                    <div class="row">
                        <h4><a href="#goals" class="mdfDashLink mdfClickToShow" data-target="goals" id="goalslink">goals</a></h4>
                    </div>
                </div>
            </div>
        </div>

        <div class="dashboard-col mdfClickContainer" id="settings">
            <div class="col-4-5 col-centered p-b-5">
                <h2 class="text-center mdfSexyWeight blue m-b-2 m-t-2">change your account settings</h2>
                {% for field in settingsForm %}
                    {% for error in field.errors %}
                        <p class="error text-center">{{ field.label|title }} {{ error }}</p>
                    {% endfor %}
                {% endfor %}
                <form class="text-center" method="post" action="{% url 'clients:account' user.username %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="mdfInputLabel">
                        <h4>Your Location:</h4>
                        {{ settingsForm.location }}
                    </div>
                    <div class="mdfFakeInput">
                        <div class="mdfInputLabel">
                            <h4>Profile Picture:</h4>
                            <h4 class="fakeInput"><a href="" id="prf" class="mdfLink">Choose a new profile picture</a></h4>
                            <h4 class="mdfFileName" id="profileImg"></h4>
                            {{ settingsForm.profile_img }}
                            {% if client.profile_img %}
                                <h4>Current profile picture:
                                    <a target="_blank" href="{{ client.profile_img.url }}" class="m-l-5 mdfLink">{{ client.photo_name }}</a>
                                    <a href="{% url 'clients:del_prof_pic' user.username %}" class="no-decor mdfRedHoverText m-l-5">x</a>
                                </h4>
                            {% endif %}
                        </div>
                    </div>
                    <div class="mdfFakeInput">
                        <div class="mdfInputLabel">
                            <h4>Banner Image:</h4>
                            <h4 class="fakeInput"><a href="" id="bnr" class="mdfLink">Choose a new banner image</a></h4>
                            <h4 class="mdfFileName" id="bannerImg"></h4>
                            {{ settingsForm.banner_img }}
                            {% if client.banner_img %}
                                <h4>Current banner image:
                                    <a target="_blank" href="{{ client.banner_img.url }}" class="m-l-5 mdfLink">{{ client.banner_photo_name }}</a>
                                    <a href="{% url 'clients:del_ban_img' user.username %}" class="no-decor mdfRedHoverText m-l-5">x</a>
                                </h4>
                            {% endif %}
                        </div>
                    </div>
                    <div class="mdfInputLabel">
                        <h4>Description:</h4>
                        {{ settingsForm.description }}
                    </div>
                    <input type="submit" name="mdfSaveClientSettings" class="mdfLogInBtn" value="Save Changes">
                </form>
            </div>
        </div>

        <div class="dashboard-col mdfClickContainer" id="goals">
            <div class="col-4-5 col-centered p-b-5">
                <div class="row m-b-2">
                    <div class="col-1-2 p-t-2">
                        <a href="#" class="no-decor pluslink slideDownForm" data-target="addgoal">
                            <img class="plusimg" src="{% static 'trainers/inc/plus.png' %}">
                        </a>
                        <p class="plusimg-brief">Add a goal</p>
                    </div>
                </div>
                <div class="row slideForm" id="addgoal">
                    <div class="col-3-4 col-centered">
                        <h2 class="text-center mdfSexyWeight blue">add a goal</h2>
                        {% for field in goalForm %}
                            {% for error in field.errors %}
                                <p class="error text-center">{{ field.label|title }} {{ error }}</p>
                            {% endfor %}
                        {% endfor %}
                        <form method="post" class="text-center" action="{% url 'clients:settings' user.username %}">
                            {% csrf_token %}
                            <div class="mdfInputLabel">
                                <h4>Add a new goal:</h4>
                                {{ goalForm.goal }}
                            </div>
                            <div class="mdfInputLabel">
                                <h4>Starting point:</h4>
                                {{ goalForm.start }}
                            </div>
                            <input type="submit" name="mdfAddGoal" class="mdfLogInBtn" value="Add Goal">
                        </form>
                    </div>
                </div>
                {% if goals %}
                    {% for goal in goals %}
                        <div class="row p-t-5">
                            <h3 class="mdfSexyWeight m-b-2">{{ goal.goal }}
                                <a href="{% url 'clients:del_goal' user.username goal.pk %}" class="m-l-5 no-decor mdfRedHoverText">x</a>
                                <a href="#" class="mdfUpdateGoal slideDownForm" data-target="updategoal_{{ goal.id }}" id="down_{{ goal.id }}">
                                    update goal
                                </a>
                            </h3>
                            <div class="row slideForm" id="updategoal_{{ goal.id }}">
                                <div class="col-3-4 col-centered">
                                    <h2 class="text-center mdfSexyWeight blue">update this goal</h2>
                                    {% for field in goalForm %}
                                        {% for error in field.errors %}
                                            <p class="error text-center">{{ field.label|title }} {{ error }}</p>
                                        {% endfor %}
                                    {% endfor %}
                                    <form method="post" class="text-center" action="{% url 'clients:settings' user.username %}">
                                        {% csrf_token %}
                                        <input type="hidden" value="{{ goal.id }}" name="goal_id">
                                        <div class="mdfInputLabel">
                                            <h4>Progress update:</h4>
                                            {{ updateGoal.update }}
                                        </div>
                                        <div class="mdfInputLabel">
                                            <h4>Increased by:</h4>
                                            {{ updateGoal.up }}
                                        </div>
                                        <div class="mdfInputLabel">
                                            <h4>Decreased by:</h4>
                                            {{ updateGoal.down }}
                                        </div>
                                        <input type="submit" name="mdfUpdateGoal" class="mdfLogInBtn" value="Update Goal">
                                    </form>
                                </div>
                            </div>
                            <div id="updates-wrapper">
                                <h4 class="mdfSexyWeight hide_updates">show updates</h4>
                                <div class="mdfFooterCopyContainer updates">
                                    {% get_updates goal.id %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <div class="row p-t-5">
                        <h3 class="mdfSexyWeight text-center">add some goals to get started on your fitness track</h3>
                    </div>
                {% endif %}
            </div>
        </div>
    {% endblock %}

    {% block javascript %}
        <script src="{% static 'splash/js/jquery.js' %}"></script>
        <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/jquery-ui.min.js"></script>
        <script src="{% static 'skeleton/skeleton.js' %}"></script>
        <script src="{% static 'clients/js/account.js' %}"></script>
    {% endblock %}

templates/clients/signup.html
{% extends 'index.html' %}
{% load static from staticfiles %}

    {% block stylesheets %}
        <link href="{% static 'skeleton/skeleton.css' %}" rel="stylesheet">
        <link href="{% static 'trainers/css/style.css' %}" rel="stylesheet">
    {% endblock %}


    {% block mdfHeaderLinks %}
        <nav role="navigation" class="nav" id="mdfNav">
            <ul class="user-links">
                <li class="blue small">already have an account?</li>
                <li id="login"><a href="{% url 'splash:login' %}" class="link">log in</a></li>
            </ul>
        </nav>
    {% endblock %}

    {% block mdfContent %}
    <div class="row" id="mdfSignUp">
        <div class="container">
            <div class="col-1-2 col-centered">
                <h1 class="mdfSexyWeight m-b-2 white text-center">Get in the best shape of your life.</h1>
                <hr class="mdfHr">
            </div>
            <div class="col-1-2 p-t-2 col-centered">
                {% for field in newclient %}
                    {% for error in field.errors %}
                        <p class="error text-center">{{ field.label|title }} {{ error }}</p>
                    {% endfor %}
                {% endfor %}
                <form action="{% url 'clients:signup' %}" id="signup-form" method="post" class="text-center">
                    {% csrf_token %}
                    {% for field in newclient %}
                        {{ field }}
                    {% endfor %}
                    <input type="submit" class="mdfLogInBtn" value="Sign Up" />
                </form>
            </div>
        </div>
    </div>
    {% endblock %}

{% block javascript %}
    <script src="{% static 'splash/js/jquery.js' %}"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/jquery-ui.min.js"></script>
    <script src="{% static 'skeleton/mask.js' %}"></script>
    <script src="{% static 'skeleton/skeleton.js' %}"></script>
    <script src="{% static 'trainers/js/trainers.js' %}"></script>
{% endblock %}

templates/clients/updates.html
{% for update in updates %}
    <h4 class="m-l-5 mdfSexyWeight m-b-2">{{ update.update }} - <span class="orange">{{ update.updated_on }}</span></h4>
{% endfor %}